"""Initial schema

Revision ID: fcd69046838b
Revises: 
Create Date: 2026-01-10 14:26:48.606671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd69046838b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funder_name', sa.String(), nullable=False),
    sa.Column('programme_name', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('TO_REVIEW', 'PURSUING', 'SUBMITTED', 'REJECTED', 'AWARDED', name='fundingstatus'), nullable=True),
    sa.Column('eligibility_criteria', sa.JSON(), nullable=True),
    sa.Column('budget_rules', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', name='projectstatus'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('print_deadline', sa.Date(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('narrative_draft', sa.Text(), nullable=True),
    sa.Column('budget_json', sa.JSON(), nullable=True),
    sa.Column('submission_status', sa.Enum('DRAFT', 'APPROVED', 'SUBMITTED', name='submissionstatus'), nullable=True),
    sa.Column('final_approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['funding_opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PHOTO', 'POSTER', 'MENU', 'AUDIO', 'VERIFICATION_DOC', name='assettype'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('rights_status', sa.Enum('UNKNOWN', 'REQUESTED', 'CLEARED', 'RESTRICTED', name='rightsstatus'), nullable=True),
    sa.Column('credit_line', sa.String(), nullable=True),
    sa.Column('usage_scope', sa.Enum('PRINT', 'DIGITAL', 'BOTH', name='usagescope'), nullable=True),
    sa.Column('is_selected_for_book', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'LOCKED', name='sectionstatus'), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('assets')
    op.drop_table('application_packages')
    op.drop_table('projects')
    op.drop_table('funding_opportunities')
    # ### end Alembic commands ###
